### ISSUE TITLE
Attribute not being recognized

### ISSUE THREAD

**Issue by GabenZone** [nosoop/SM-TFCW3toX#3] opened 2024-02-20 16:48 UTC
Ive been trying to get the "hotsauce on hit" attribute from Orion's Attributes to work with Custom Weapons X, but no matter what i do or change in the config it always keeps saying the same error message, which is:

"[cw3toX.smx] WARNING! Attribute hotsauce on hit (value "1.0 8.0" plugin "orion") seems to have been ignored by all attribute plugins. It's either an invalid attribute, incorrect plugin, an error occured in the att. plugin, or the att. plugin forgot to return Plugin_Handled."

Im not sure if im doing something wrong, or if this attribute doesnt work all together so help would be appreciated.

![image](https://github.com/nosoop/SM-TFCW3toX/assets/39264330/ee9702ef-ba0a-465e-9457-e949f2c74b64)

**Comment by nosoop** [comment] 2024-02-21 07:40
Check your error logs and `sm plugins list` / `sm plugins info orion.smx` to verify that the plugin is loaded and not raising any issues.

**Comment by GabenZone** [comment] 2024-02-21 14:12
Just checked and no, it's not raising any errors and it's loaded in.
![image](https://github.com/nosoop/SM-TFCW3toX/assets/39264330/4a18d232-a10d-467b-b651-2952ca952692)

**Comment by nosoop** [comment] 2024-02-21 23:04
Judging by the date, it looks like you have [the CW2 version](https://forums.alliedmods.net/showpost.php?p=2193855&postcount=254) installed.  I have tested and confirmed that [the CW3 version](https://forums.alliedmods.net/showpost.php?p=2436927&postcount=4) doesn't raise any errors (though whether or not the attribute actually functions is not the responsibility of cw3toX).

**Comment by nosoop** [comment] 2024-02-25 05:22
Since I believe that the problem has been correctly identified, I'll consider this resolved and close it.
(The CW2 version is not supported due to fundamental incompatibilities in its API design; see #2 for an explanation on that.)

**Closed as completed by nosoop** 2024-02-25 05:22 UTC
